/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.DLImageTaskReply', null, global);
goog.exportSymbol('proto.DLImageTaskRequest', null, global);
goog.exportSymbol('proto.DLStreamingTaskReply', null, global);
goog.exportSymbol('proto.DLStreamingTaskRequest', null, global);
goog.exportSymbol('proto.DLVideoTaskReply', null, global);
goog.exportSymbol('proto.DLVideoTaskRequest', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.DLStreamingTaskRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.DLStreamingTaskRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.DLStreamingTaskRequest.displayName = 'proto.DLStreamingTaskRequest';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.DLStreamingTaskRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.DLStreamingTaskRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.DLStreamingTaskRequest} msg The msg instance to transform.
 * @return {!Object}
 */
proto.DLStreamingTaskRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    taskName: msg.getTaskName(),
    image: msg.getImage_asB64()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.DLStreamingTaskRequest} The clone.
 */
proto.DLStreamingTaskRequest.prototype.cloneMessage = function() {
  return /** @type {!proto.DLStreamingTaskRequest} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional string task_name = 1;
 * @return {string}
 */
proto.DLStreamingTaskRequest.prototype.getTaskName = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 1, ""));
};


/** @param {string} value  */
proto.DLStreamingTaskRequest.prototype.setTaskName = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional bytes image = 2;
 * @return {string}
 */
proto.DLStreamingTaskRequest.prototype.getImage = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 2, ""));
};


/**
 * optional bytes image = 2;
 * This is a type-conversion wrapper around `getImage()`
 * @return {string}
 */
proto.DLStreamingTaskRequest.prototype.getImage_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getImage()));
};


/**
 * optional bytes image = 2;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getImage()`
 * @return {!Uint8Array}
 */
proto.DLStreamingTaskRequest.prototype.getImage_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getImage()));
};


/** @param {!(string|Uint8Array)} value  */
proto.DLStreamingTaskRequest.prototype.setImage = function(value) {
  jspb.Message.setField(this, 2, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.DLStreamingTaskReply = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.DLStreamingTaskReply, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.DLStreamingTaskReply.displayName = 'proto.DLStreamingTaskReply';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.DLStreamingTaskReply.prototype.toObject = function(opt_includeInstance) {
  return proto.DLStreamingTaskReply.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.DLStreamingTaskReply} msg The msg instance to transform.
 * @return {!Object}
 */
proto.DLStreamingTaskReply.toObject = function(includeInstance, msg) {
  var f, obj = {
    image: msg.getImage_asB64()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.DLStreamingTaskReply} The clone.
 */
proto.DLStreamingTaskReply.prototype.cloneMessage = function() {
  return /** @type {!proto.DLStreamingTaskReply} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional bytes image = 1;
 * @return {string}
 */
proto.DLStreamingTaskReply.prototype.getImage = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 1, ""));
};


/**
 * optional bytes image = 1;
 * This is a type-conversion wrapper around `getImage()`
 * @return {string}
 */
proto.DLStreamingTaskReply.prototype.getImage_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getImage()));
};


/**
 * optional bytes image = 1;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getImage()`
 * @return {!Uint8Array}
 */
proto.DLStreamingTaskReply.prototype.getImage_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getImage()));
};


/** @param {!(string|Uint8Array)} value  */
proto.DLStreamingTaskReply.prototype.setImage = function(value) {
  jspb.Message.setField(this, 1, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.DLImageTaskRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.DLImageTaskRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.DLImageTaskRequest.displayName = 'proto.DLImageTaskRequest';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.DLImageTaskRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.DLImageTaskRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.DLImageTaskRequest} msg The msg instance to transform.
 * @return {!Object}
 */
proto.DLImageTaskRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    taskName: msg.getTaskName(),
    image: msg.getImage_asB64(),
    bbox: msg.getBbox()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.DLImageTaskRequest} The clone.
 */
proto.DLImageTaskRequest.prototype.cloneMessage = function() {
  return /** @type {!proto.DLImageTaskRequest} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional string task_name = 1;
 * @return {string}
 */
proto.DLImageTaskRequest.prototype.getTaskName = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 1, ""));
};


/** @param {string} value  */
proto.DLImageTaskRequest.prototype.setTaskName = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional bytes image = 2;
 * @return {string}
 */
proto.DLImageTaskRequest.prototype.getImage = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 2, ""));
};


/**
 * optional bytes image = 2;
 * This is a type-conversion wrapper around `getImage()`
 * @return {string}
 */
proto.DLImageTaskRequest.prototype.getImage_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getImage()));
};


/**
 * optional bytes image = 2;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getImage()`
 * @return {!Uint8Array}
 */
proto.DLImageTaskRequest.prototype.getImage_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getImage()));
};


/** @param {!(string|Uint8Array)} value  */
proto.DLImageTaskRequest.prototype.setImage = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional string bbox = 3;
 * @return {string}
 */
proto.DLImageTaskRequest.prototype.getBbox = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 3, ""));
};


/** @param {string} value  */
proto.DLImageTaskRequest.prototype.setBbox = function(value) {
  jspb.Message.setField(this, 3, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.DLImageTaskReply = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.DLImageTaskReply, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.DLImageTaskReply.displayName = 'proto.DLImageTaskReply';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.DLImageTaskReply.prototype.toObject = function(opt_includeInstance) {
  return proto.DLImageTaskReply.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.DLImageTaskReply} msg The msg instance to transform.
 * @return {!Object}
 */
proto.DLImageTaskReply.toObject = function(includeInstance, msg) {
  var f, obj = {
    taskName: msg.getTaskName(),
    image: msg.getImage_asB64()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.DLImageTaskReply} The clone.
 */
proto.DLImageTaskReply.prototype.cloneMessage = function() {
  return /** @type {!proto.DLImageTaskReply} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional string task_name = 1;
 * @return {string}
 */
proto.DLImageTaskReply.prototype.getTaskName = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 1, ""));
};


/** @param {string} value  */
proto.DLImageTaskReply.prototype.setTaskName = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional bytes image = 2;
 * @return {string}
 */
proto.DLImageTaskReply.prototype.getImage = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 2, ""));
};


/**
 * optional bytes image = 2;
 * This is a type-conversion wrapper around `getImage()`
 * @return {string}
 */
proto.DLImageTaskReply.prototype.getImage_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getImage()));
};


/**
 * optional bytes image = 2;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getImage()`
 * @return {!Uint8Array}
 */
proto.DLImageTaskReply.prototype.getImage_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getImage()));
};


/** @param {!(string|Uint8Array)} value  */
proto.DLImageTaskReply.prototype.setImage = function(value) {
  jspb.Message.setField(this, 2, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.DLVideoTaskRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.DLVideoTaskRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.DLVideoTaskRequest.displayName = 'proto.DLVideoTaskRequest';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.DLVideoTaskRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.DLVideoTaskRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.DLVideoTaskRequest} msg The msg instance to transform.
 * @return {!Object}
 */
proto.DLVideoTaskRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    taskName: msg.getTaskName(),
    videoPath: msg.getVideoPath(),
    bbox: msg.getBbox()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.DLVideoTaskRequest} The clone.
 */
proto.DLVideoTaskRequest.prototype.cloneMessage = function() {
  return /** @type {!proto.DLVideoTaskRequest} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional string task_name = 1;
 * @return {string}
 */
proto.DLVideoTaskRequest.prototype.getTaskName = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 1, ""));
};


/** @param {string} value  */
proto.DLVideoTaskRequest.prototype.setTaskName = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional string video_path = 2;
 * @return {string}
 */
proto.DLVideoTaskRequest.prototype.getVideoPath = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 2, ""));
};


/** @param {string} value  */
proto.DLVideoTaskRequest.prototype.setVideoPath = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional string bbox = 3;
 * @return {string}
 */
proto.DLVideoTaskRequest.prototype.getBbox = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 3, ""));
};


/** @param {string} value  */
proto.DLVideoTaskRequest.prototype.setBbox = function(value) {
  jspb.Message.setField(this, 3, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.DLVideoTaskReply = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.DLVideoTaskReply, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.DLVideoTaskReply.displayName = 'proto.DLVideoTaskReply';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.DLVideoTaskReply.prototype.toObject = function(opt_includeInstance) {
  return proto.DLVideoTaskReply.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.DLVideoTaskReply} msg The msg instance to transform.
 * @return {!Object}
 */
proto.DLVideoTaskReply.toObject = function(includeInstance, msg) {
  var f, obj = {
    success: msg.getSuccess()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.DLVideoTaskReply} The clone.
 */
proto.DLVideoTaskReply.prototype.cloneMessage = function() {
  return /** @type {!proto.DLVideoTaskReply} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional bool success = 1;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.DLVideoTaskReply.prototype.getSuccess = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldProto3(this, 1, false));
};


/** @param {boolean} value  */
proto.DLVideoTaskReply.prototype.setSuccess = function(value) {
  jspb.Message.setField(this, 1, value);
};


goog.object.extend(exports, proto);
